on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  autodocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: |
          zig build-lib -femit-docs src/ulid.zig
          mv docs _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: zig build test --summary all

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - autodocs
      - test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
